language: java
jdk:
- oraclejdk8
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: robgarciab@gmail.com
  password:
    secure: gZR2ouyl7netx1knqOareXpThbM0vEToDVQsDFNCp7abSLo+zJ38TKiDE7k0sHbEKjpAoSQUaDSqN5J1rNU6me0bRuuP36aPfXEMPkY72utn5MZYOXoEaK9ZqFJGYO3HG9GaW/WaGm0WM6iB/CcVTAxUoM0Ay1sXZ+8EUQkodyYVHpb456aRV1ghwh5QKv8HMYJKsdpO5soj6zteVkCBpToZ/oal/SgFzETEmlkP3ya9yJPAaKQnVpV8RzN5RHt2rIY1LlGon62YM/Z4YxUSQ1G0C9LC33cxaAFWOG+ztTtyikgMUlyWW5iRkWVKhi4N3dSLxsxRPbhFiq8lAun05YQQQgfA9vlq0eTJXmjm0KSSBz13GGn973CNgJeZBS3/bXmbjOzSpsSAXHlAJ6s4DOni821UDZDwF63Ow4r1BMaO4hT06cfWBQU02S8XFa0MC+VwVx1eFIj5wI64choLMLhkmW37dT3jYhEqyDISRjIhpBfJwUVQXwdDA2B6khCZjnwsfX/BaHy6POVTlGze2dsAD4fi3JgAkQW736cq50nsee/Iwarj7IaFIubOXwjkR2pwSjMA0zSKjC31Lq7o+sHPs9D4qOWGsh1HH1hxlrfRPvWv2CEz9MmTOcjeEeMz5yppfvD/3g6JGZAZ8+kMv3DQChbXKukIFwn1jcZQzkY=
  organization: katari
  space: development
